version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  fake-smtp-server:
    image: gessnerfl/fake-smtp-server
    ports:
      - 5025:5025
      - 5080:5080
      - 5081:5081